# Generated by Django 4.2.6 on 2023-10-20 07:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_auth_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'heic', 'heif'])]),
        ),
    ]
